name: Dependency review

on:
  pull_request:
    branches:
      - main

jobs:
  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Scan
        uses: actions/dependency-review-action@v4
        with:
          comment-summary-in-pr: true
          allow-licenses: "EPL-1.0,LGPL-2.1,LGPL-2.1-only"